project:
  type: website
  output-dir: docs

website:
  title: "SAMUEL GAMITO"
  navbar:
    background: "#0f172a" # Tu color Slate 900 (Autoridad)
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: Home
      - href: dashboards.qmd # Placeholder para el futuro
        text: Datos CNMC
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/samuel-gamito-matellan/
      - icon: github
        href: https://github.com/samuelgamito-Energy

format:
  html:
    theme: 
      light: flatly      # Limpio y estructurado para leer de día
      dark: darkly       # Modo oscuro automático para entornos de trading
    css: styles.css
    toc: true
    mainfont: "Segoe UI" # La fuente que usas en tus dashboards