project:
  type: website
  output-dir: docs
  resources: 
    - "VideoFractales.mp4"
    - "logic.js"      # IMPORTANTE: Para que funcionen los datos del dashboard
    - "custom.css"    # IMPORTANTE: Para que se copien los estilos del dashboard

website:
  title: "SAMUEL GAMITO"
  navbar:
    background: "#0f172a"
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Energy Flash
      - href: dashboards.qmd
        text: Market Intelligence
      - href: sector.qmd
        text: Sector Analytics
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/samuel-gamito-matellan/
      - icon: github
        href: https://github.com/samuelgamito-Energy

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    mainfont: "Segoe UI"